name: Go
on: 
  push:
    branches:
    - master
    paths:
    - '*'
    - '!azure-pipelines.yml'
    - '!.travis.yml'
    - '!*.md'
    
    
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-18.04]
        goos: [ linux, windows ]
        arch: [amd64, arm]
        go: [ '1.12' ]
        exclude:
          - goos: windows
            arch: arm        

    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Generate swagger docs
      run: |
        go get -u github.com/swaggo/swag/cmd/swag
        export PATH=$PATH:$(go env GOPATH)/bin
        go build github.com/pufferpanel/pufferd/v2
        swag init --parseDependency -g routing/root.go
      
    - name: Build
      run: |
        go build -ldflags "-X github.com/pufferpanel/pufferd/version.Hash=${{ github.sha }}" -v github.com/pufferpanel/pufferd/v2
